### ISSUE TITLE
Redirect to SWITCHcast no longer working

### ISSUE THREAD

**Issue by lorenzulrich** [ndunand/moodle-mod_opencast#16]
SWITCHcast changed the stream security configuration of its Opencast server, leading to the Opencast plugin no longer redirecting to the annotation tool.

When trying to redirect to the annotation tool, the following code requests a signed URL from Opencast:

https://github.com/ndunand/moodle-mod_opencast/blob/master/go_to.php#L84

This no leads to the following fatal error:

```
«Given URL cannot be signed»
```

I contacted SWITCH about this and I got the following reply:

> We have indeed adjusted our stream security configuration in the last few weeks to eliminate inconsistencies that were causing problems elsewhere. In concrete terms, this means that Opencast now no longer signs some URLs, as these do not need to be signed at all, i.e. the signature is not checked at all. The URL should therefore be valid even without a signature.
> 
> Is there perhaps the possibility to configure this in the plugin? :/
> 
> Translated with www.DeepL.com/Translator (free version)

How should we handle this?

**Comment by ndunand** [comment]
Hi @lorenzulrich ,

I have just pushed a commit that should fix this.

**Comment by lorenzulrich** [comment]
@ndunand Sorry for the late reply: Yes, it fixed the issue - thanks!
