### ISSUE TITLE
Item Ordering

### ISSUE THREAD

**Issue by leblzhaw** [ndunand/moodle-mod_opencast#18]
Hello all,
Its not really an issue more like a feature request.

When creating a SWITCHcast/OpenCast channel on Moodle and uploading videos, it used to be that the videos were displayed sorted alphanumerically by name.

Now they are displayed sorted by date. This means that the lecturers always have to upload the videos one after the other and the display order can no longer be adjusted afterwards.

Can you make it possible to display the videos sorted by name alphanumerically again?

Best regards
Sascha

**Comment by ndunand** [comment]
Hi,
This probably is not due to a plugin change as there hasn't been any recently.
You can always click on column headers to sort as wanted.

**Comment by leblzhaw** [comment]
Hi,
the topic was brought to my attention by a lecturer who encountered this behavior some time ago and thus named her videos alphanumerically. The change from standard title to standard timestamp has probably already taken place some time ago. 

However, she has now decided not to follow up on this issue.

Best regards
Sascha

**Comment by ndunand** [comment]
Hi,
Alright thanks for reporting back
